---
title       : ETFs vs. Mutual Funds
subtitle    : Effects of Costs on Returns
author      : Strawberry Socialist
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Saving for Retirement

In today's world, we are on our own. Gone are the days of a guaranteed income in our old age. Now, if we don't save enough and invest sagely, we may face our old age in penury.  

The first piece of advice most people hear is about the importance of diversification. Aside from buying a bunch of individual stocks and bonds, the main way for individual investors to diversfy is to buy a fund.  

There are two main types of funds available to retail investors: exchange traded funds (ETFs) and mutual funds. These funds are fundamentally different and have different cost structures.

### Types of Costs

There are three categories of costs with most exchange traded funds and mutual funds.
* Overhead Costs (Expense Ratios)
* Transaction Costs (Commissions, Market Impact, Bid/Ask
* Other Costs (Cash Drag, Tax)

--- .class #id 

## Average Costs

The average costs for the following types of ETFs and Mutual Funds.

_Overhead Costs (Expense Ratios)_
* ETF: 0.44%  
* Mutual Fund: 0.74%  (Passive) to 0.90%  (Active)

_Transaction Costs (Commissions, Market Impact, Bid/Ask)_
* ETF: 0.21% (NAV < $10 billion) to 1.91% (NAV < $50 million)
* Mutual Fund: 1.44% (Passive)

_Other Costs (Cash Drag, Tax)_
* ETF: 0.74%
* Mutual Fund: 0.83%

---

## Effect of Average Costs on ETF Returns

The total costs that apply to an average US focused large cap ETF is `r (0.0044+0.0021+0.0074)*100`%. If you invested $10,000 in the average US focused large cap ETF with only a 5% average annual return over 20 years you'd end up with `r format(10000*((1+(0.05-(0.0044+0.0021+0.0074))))^20,nsmall=2,decimal.mark=".",big.mark=",")`.

Largely due to liquidity issues the total costs that apply to an average US focused small cap ETF are much larger at `r (0.0044+0.0191+0.0074)*100`%. If you invested in the average US focused small cap ETF instead you would get a return of `r format(10000*((1+(0.05-(0.0044+0.0191+0.0074))))^20,nsmall=2,decimal.mark=".",big.mark=",")`.

Now, if you were somehow able to make an investment with no costs under the same conditions, you would end up with a return of `r format(10000*((1+(0.05-(0))))^20,nsmall=2,decimal.mark=".",big.mark=",")`.

As you can see a `r (0.0044+0.0021+0.0074)*100`% cost results in a loss of `r format((10000*((1+(0.05-(0))))^20) - (10000*((1+(0.05-(0.0044+0.0021+0.0074))))^20),nsmall=2,decimal.mark=".",big.mark=",")` over 20 years. Whereas a total cost of `r (0.0044+0.0191+0.0074)*100`% looses you `r format((10000*((1+(0.05-(0))))^20) - (10000*((1+(0.05-(0.0044+0.0191+0.0074))))^20),nsmall=2,decimal.mark=".",big.mark=",")`

---

## Effect of Average Costs on Mutual Fund Returns

The total costs that apply to the average passive index-tracking mutual fund is `r (0.0074+0.0144+0.0083)*100`%. If you invested $10,000 in an passive index-tracking mutual fund with only a 5% average annual return over 20 years you'd end up with `r format(10000*((1+(0.05-(0.0074+0.0144+0.0083))))^20,nsmall=2,decimal.mark=".",big.mark=",")`.

The total costs that apply to the average active mutual fund are likely larger than a conservative estimate of `r (0.0090+0.0144+0.0083)*100`%. If you invested in an average active mutual fund instead you would get a return of `r format(10000*((1+(0.05-(0.0090+0.0144+0.0083))))^20,nsmall=2,decimal.mark=".",big.mark=",")`.  

Note: Since active funds trade in and out of positions more frequently they incur larger transaction costs. However since these vary quite a bit I was unable to find a reputable estimate. Therefore these figures used the average transaction costs incurred by passive mutual funds. 

Now, if you were somehow able to make an investment with no costs under the same conditions, you would end up with a return of `r format(10000*((1+(0.05-(0))))^20,nsmall=2,decimal.mark=".",big.mark=",")`.

As you can see a `r (0.0074+0.0144+0.0083)*100`% cost results in a loss of `r format((10000*((1+(0.05-(0))))^20) - (10000*((1+(0.05-(0.0074+0.0144+0.0083))))^20),nsmall=2,decimal.mark=".",big.mark=",")` over 20 years. Whereas a total cost of `r (0.0090+0.0144+0.0083)*100`% looses you `r format((10000*((1+(0.05-(0))))^20) - (10000*((1+(0.05-(0.0090+0.0144+0.0083))))^20),nsmall=2,decimal.mark=".",big.mark=",")`

---

## Conclusion

With the steep decline of defined benefit pensions your ability to live even moderately comfortable in your old age depend heavily on your investment decisions. While there are many investment professionals to help you make these decisions, it helps to have some independent basis to evaluate their recommendations.  

As mentioned earlier diversification is the main route to minimize the risk of loosing a significant portion of your retirement savings. Investing in one or more funds is an easy way to automatically diversify your investment portfolio. However, even relatively small differences in the costs associated with different types of funds and individual funds can seriously eat into your returns over the long run. 

So when making investment decisions, either on your own or with the help of an investment professional, carefully review all the costs associated with that type of fund and the specifics of the funds you are considering. Do not just look at the expense ratio. Remember that the average expense ratio of an ETF is 0.44% while the average passive index-tracking mutual fund is only 0.30% more at 0.74%. However, when the total costs are considered the difference in the expected returns is `r format((10000*((1+(0.05-(0.0044+0.0191+0.0074))))^20) - (10000*((1+(0.05-(0.0090+0.0144+0.0083))))^20),nsmall=2,decimal.mark=".",big.mark=",")`.
